apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

data:
  type: {{ "git" | b64enc }}
  url: {{ .Values.repoURL | b64enc}}
  project: {{ .Values.project  | b64enc}}
  githubAppID: {{ .Values.github_app.id  | b64enc}}
  githubAppInstallationID: {{ .Values.github_app.install_id  | b64enc}}
  githubAppPrivateKey: {{ .Values.github_app.private_key  | b64enc}}
 