apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- operator.yaml
- knative_serving.yaml
- net_cert_manager.yaml

namespace: {{ .Values.namespace }}

patches:

- patch: |-
    - op: replace
      path: /spec
      value: 
        acme:
          privateKeySecretRef:
            name: knative-selfsigned-issuer-account-key

          server: https://acme-v02.api.letsencrypt.org/directory

          solvers:
          - http01:
              ingress:
                class: kourier

  target:
    kind: ClusterIssuer
    name: knative-selfsigned-issuer

- patch: |-
    - op: replace
      path: /data
      value: 
        issuerRef: |
          kind: ClusterIssuer
          name: letsencrypt-http01-issuer

  target:
    kind: ConfigMap
    name: config-certmanager
    namespace: {{ .Values.namespace }}