apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-{{ .Values.aws_region }}-parameter-store

spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws_region }}
      auth:
        jwt:
          serviceAccountRef:
            name: parameter-store-read
            namespace: external-secrets