apiVersion: v1
kind: ServiceAccount
metadata:
  name: parameter-store-read
  namespace: external-secrets

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws_account_id }}:role/{{ .Values.role_name }}