apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamodb-access

  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws_account_id }}:role/{{ .Values.dynamodb_access_role_name }}"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access

  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws_account_id }}:role/{{ .Values.s3_access_role_name }}"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatgpt-helper

  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws_account_id }}:role/{{ .Values.chatgpt_helper_role_name }}"