apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helm_kustomize_plugin_cm.yaml
- helm_kustomize_plugin_deployment.yaml

patches:
  - path: helm_kustomize_plugin_deployment.yaml
