apiVersion: v1
kind: ServiceAccount
metadata:
  name: jarvis-irsa

  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws_account_id }}:role/{{ .Values.incident_response_access_role }}"