apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-issuer

spec:
  acme:
    privateKeySecretRef:
      name: knative-issuer-account-key

    server: https://acme-v02.api.letsencrypt.org/directory

    solvers:
    - http01:
       ingress:
         class: kourier